parameters:
doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        url: '%env(DATABASE_URL)%'
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App\Domain:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Domain'
        prefix: App\Domain
        alias: App\Domain
      App\Infrastructure\Doctrine:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Infrastructure/Doctrine'
        prefix: App\Infrastructure\Doctrine
        alias: App\Infrastructure\Doctrine
